obj-$(CONFIG_RPMSG)	+= virtio_rpmsg_bus.o
obj-$(CONFIG_RPMSG_SERVER_SAMPLE) += rpmsg_server_sample.o
obj-$(CONFIG_RPMSG_FREERTOS_STAT) += rpmsg_freertos_statistic.o
obj-$(CONFIG_RPMSG_ZYNQ) += zynq_rpmsg.o
obj-$(CONFIG_RPMSG_USER_DEV) += rpmsg_user_dev.o
